services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data:Z
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: ./multimessage
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./multimessage:/app:Z
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
