services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data:Z
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  web:  
    build: ./multimessage
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - "./data/${SIGNAL_CLI_CONFIG}:/app/${SIGNAL_CLI_CONFIG}:Z"
      - "./multimessage:/app:Z"


