# Generated by Django 5.0 on 2023-12-26 16:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ContactList",
            new_name="Group",
        ),
    ]
