# Generated by Django 5.0 on 2024-01-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_rename_contactlist_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='uuid',
            field=models.CharField(default='xxxxxxxxxxxxxxxxxx', max_length=64),
            preserve_default=False,
        ),
    ]
