# Generated by Django 5.0 on 2024-01-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='uuid',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
