# Generated by Django 5.0 on 2024-01-07 19:07

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_contact_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='contact',
            name='uuid',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
